# yaml-language-server: $schema=https://raw.githubusercontent.com/Ensono/eirctl/refs/heads/main/schemas/schema_v1.json

import:
  - https://raw.githubusercontent.com/Ensono/stacks-eirctl-configurations/refs/tags/v0.1.14/shared/contexts/eirctl.yaml
  - https://raw.githubusercontent.com/Ensono/stacks-eirctl-configurations/refs/tags/v0.1.14/shared/security/eirctl.yaml
  - https://raw.githubusercontent.com/Ensono/stacks-eirctl-configurations/refs/tags/v0.1.14/shared/docs/eirctl.yaml
  - https://raw.githubusercontent.com/Ensono/stacks-eirctl-configurations/refs/tags/v0.1.14/shared/infra/terraform.yaml
  - https://raw.githubusercontent.com/Ensono/stacks-eirctl-configurations/refs/tags/v0.1.14/shared/github/eirctl.yaml

watchers:
  lint:
    watch: ["*.yml"]
    events: [create, write]
    task: lint:yaml
  terraform:
    watch: ["*.tf", "*.tfvars"]
    events: [create, write]
    task: lint:terraform:format

pipelines:
  build:
    - task: terraform:build:clean
    - task: terraform:docs:asciidoc
      depends_on: terraform:build:clean
    - task: docs:docbook
      depends_on: terraform:docs:asciidoc
    - task: docs:markdown
      depends_on: docs:docbook
    - task: terraform:build:copy
      depends_on: docs:markdown
    - task: terraform:build:package
      depends_on: terraform:build:copy

  docs:
    - task: docs:generate

  scan:
    - task: scan:terraform:checkov

  lint:
    - task: lint:terraform:validate
    - task: lint:terraform:tflint
      depends_on: lint:terraform:validate

  tests:
    - task: terraform:init:false
    - task: terraform:tests
      depends_on: terraform:init:false

  release:
    - task: github:release
