locals {
  # Resource names for policy default values
  # These must be known at plan time (no random suffix) to avoid for_each errors in the ALZ module
  # Uses provider::azapi::resource_group_resource_id() for predictable resource IDs

  # Resource names
  policy_resource_group_name          = module.naming["management"].resource_group.name
  policy_log_analytics_workspace_name = module.naming["management"].log_analytics_workspace.name

  # DCR and UAI names - match defaults from avm-ptn-alz-management module
  # These use the module defaults as they're not generated by the naming module
  policy_dcr_change_tracking_name = try(var.management_resource_settings.data_collection_rules.change_tracking.name, "dcr-change-tracking")
  policy_dcr_defender_sql_name    = try(var.management_resource_settings.data_collection_rules.defender_sql.name, "dcr-defender-sql")
  policy_dcr_vm_insights_name     = try(var.management_resource_settings.data_collection_rules.vm_insights.name, "dcr-vm-insights")
  policy_uai_ama_name             = try(var.management_resource_settings.user_assigned_managed_identities.ama.name, "uai-ama")

  # Feature flags for DCRs
  dcr_change_tracking_enabled = try(var.management_resource_settings.data_collection_rules.change_tracking.enabled, true)
  dcr_defender_sql_enabled    = try(var.management_resource_settings.data_collection_rules.defender_sql.enabled, false)
  dcr_vm_insights_enabled     = try(var.management_resource_settings.data_collection_rules.vm_insights.enabled, true)
  uai_ama_enabled             = try(var.management_resource_settings.user_assigned_managed_identities.ama.enabled, true)

  # Policy values - only compute for enabled resources
  policy_values_from_resources = var.management_resources_enabled ? merge(
    # Change Tracking DCR (enabled by default)
    local.dcr_change_tracking_enabled ? {
      ama_change_tracking_data_collection_rule_id = provider::azapi::resource_group_resource_id(
        var.management_subscription_id,
        local.policy_resource_group_name,
        "Microsoft.Insights/dataCollectionRules",
        [local.policy_dcr_change_tracking_name]
      )
    } : {},
    # Defender for SQL DCR (disabled by default)
    local.dcr_defender_sql_enabled ? {
      ama_mdfc_sql_data_collection_rule_id = provider::azapi::resource_group_resource_id(
        var.management_subscription_id,
        local.policy_resource_group_name,
        "Microsoft.Insights/dataCollectionRules",
        [local.policy_dcr_defender_sql_name]
      )
    } : {},
    # VM Insights DCR (enabled by default)
    local.dcr_vm_insights_enabled ? {
      ama_vm_insights_data_collection_rule_id = provider::azapi::resource_group_resource_id(
        var.management_subscription_id,
        local.policy_resource_group_name,
        "Microsoft.Insights/dataCollectionRules",
        [local.policy_dcr_vm_insights_name]
      )
    } : {},
    # AMA User Assigned Identity (enabled by default)
    local.uai_ama_enabled ? {
      ama_user_assigned_managed_identity_id = provider::azapi::resource_group_resource_id(
        var.management_subscription_id,
        local.policy_resource_group_name,
        "Microsoft.ManagedIdentity/userAssignedIdentities",
        [local.policy_uai_ama_name]
      )
      ama_user_assigned_managed_identity_name = local.policy_uai_ama_name
    } : {},
    # Log Analytics Workspace (always created when management_resources_enabled)
    {
      log_analytics_workspace_id = provider::azapi::resource_group_resource_id(
        var.management_subscription_id,
        local.policy_resource_group_name,
        "Microsoft.OperationalInsights/workspaces",
        [local.policy_log_analytics_workspace_name]
      )
    }
  ) : {}

  # JSON-encoded for ALZ module (excludes null/empty values)
  policy_values_encoded = {
    for k, v in local.policy_values_from_resources :
    k => jsonencode({ value = v })
    if v != null && v != ""
  }

  policy_default_values = merge(
    local.policy_values_encoded,
    try(coalesce(var.management_group_settings.policy_default_values, {}), {})
  )

  # Default policy assignments to modify (disables policies for features not deployed)
  # Note: Parameters must be JSON-encoded with { value = ... } format per ALZ module requirements
  #
  # Defender plan and sub-feature toggles are driven by var.microsoft_defender_settings.
  # Boolean toggles are mapped to policy parameter values here.
  default_policy_assignments_to_modify = {
    alz = {
      policy_assignments = {
        # Microsoft Defender for Cloud
        Deploy-MDFC-Config-H224 = {
          parameters = {
            ascExportResourceGroupLocation = jsonencode({ value = var.location })
            ascExportResourceGroupName     = jsonencode({ value = var.microsoft_defender_settings.export_resource_group_name })
            emailSecurityContact           = jsonencode({ value = var.microsoft_defender_settings.email_security_contact })

            # Defender plans - true = "DeployIfNotExists", false = "Disabled"
            enableAscForAI                              = jsonencode({ value = var.microsoft_defender_settings.defender_plans.ai ? "DeployIfNotExists" : "Disabled" })
            enableAscForAppServices                     = jsonencode({ value = var.microsoft_defender_settings.defender_plans.app_services ? "DeployIfNotExists" : "Disabled" })
            enableAscForArm                             = jsonencode({ value = var.microsoft_defender_settings.defender_plans.arm ? "DeployIfNotExists" : "Disabled" })
            enableAscForContainers                      = jsonencode({ value = var.microsoft_defender_settings.defender_plans.containers ? "DeployIfNotExists" : "Disabled" })
            enableAscForCosmosDbs                       = jsonencode({ value = var.microsoft_defender_settings.defender_plans.cosmos_dbs ? "DeployIfNotExists" : "Disabled" })
            enableAscForCspm                            = jsonencode({ value = var.microsoft_defender_settings.defender_plans.cspm ? "DeployIfNotExists" : "Disabled" })
            enableAscForKeyVault                        = jsonencode({ value = var.microsoft_defender_settings.defender_plans.key_vault ? "DeployIfNotExists" : "Disabled" })
            enableAscForOssDb                           = jsonencode({ value = var.microsoft_defender_settings.defender_plans.oss_db ? "DeployIfNotExists" : "Disabled" })
            enableAscForServers                         = jsonencode({ value = var.microsoft_defender_settings.defender_plans.servers ? "DeployIfNotExists" : "Disabled" })
            enableAscForServersVulnerabilityAssessments = jsonencode({ value = var.microsoft_defender_settings.defender_plans.servers_vulnerability_assessments ? "DeployIfNotExists" : "Disabled" })
            enableAscForSql                             = jsonencode({ value = var.microsoft_defender_settings.defender_plans.sql ? "DeployIfNotExists" : "Disabled" })
            enableAscForSqlOnVm                         = jsonencode({ value = var.microsoft_defender_settings.defender_plans.sql_on_vm ? "DeployIfNotExists" : "Disabled" })
            enableAscForStorage                         = jsonencode({ value = var.microsoft_defender_settings.defender_plans.storage ? "DeployIfNotExists" : "Disabled" })
            enableTvmCheck                              = jsonencode({ value = var.microsoft_defender_settings.defender_plans.tvm_check ? "DeployIfNotExists" : "Disabled" })

            # Sub-features - true = "true", false = "false"
            ascForAIIsAIPromptEvidenceEnabled                              = jsonencode({ value = tostring(var.microsoft_defender_settings.subfeatures.ai_prompt_evidence) })
            ascForCspmIsAgentlessDiscoveryForKubernetesEnabled             = jsonencode({ value = tostring(var.microsoft_defender_settings.subfeatures.cspm_agentless_discovery_for_kubernetes) })
            ascForCspmIsAgentlessVmScanningEnabled                         = jsonencode({ value = tostring(var.microsoft_defender_settings.subfeatures.cspm_agentless_vm_scanning) })
            ascForCspmIsContainerRegistriesVulnerabilityAssessmentsEnabled = jsonencode({ value = tostring(var.microsoft_defender_settings.subfeatures.cspm_container_registries_vulnerability_assessments) })
            ascForCspmIsEntraPermissionsManagementEnabled                  = jsonencode({ value = tostring(var.microsoft_defender_settings.subfeatures.cspm_entra_permissions_management) })
            ascForCspmIsSensitiveDataDiscoveryEnabled                      = jsonencode({ value = tostring(var.microsoft_defender_settings.subfeatures.cspm_sensitive_data_discovery) })
            ascForServersIsAgentlessVmScanningEnabled                      = jsonencode({ value = tostring(var.microsoft_defender_settings.subfeatures.servers_agentless_vm_scanning) })
            ascForStorageIsOnUploadMalwareScanningEnabled                  = jsonencode({ value = tostring(var.microsoft_defender_settings.subfeatures.storage_on_upload_malware_scanning) })
            ascForStorageIsSensitiveDataDiscoveryEnabled                   = jsonencode({ value = tostring(var.microsoft_defender_settings.subfeatures.storage_sensitive_data_discovery) })
          }
        }
      }
    }
    # NOTE: Enable-DDoS-VNET is removed from connectivity and landing_zones archetypes
    # in the lib/archetype_definitions/*_custom.alz_archetype_override.yaml files.
    # Only modify policies that exist in the architecture.
    corp = {
      policy_assignments = {
        Deploy-Private-DNS-Zones = {
          enforcement_mode = "DoNotEnforce"
        }
      }
    }
  }

  policy_assignments_to_modify = merge(
    local.default_policy_assignments_to_modify,
    try(coalesce(var.management_group_settings.policy_assignments_to_modify, {}), {})
  )
}
