locals {
  # Resource names for policy default values
  # These must be known at plan time (no random suffix) to avoid for_each errors in the ALZ module
  # Uses provider::azapi::resource_group_resource_id() for predictable resource IDs

  # Resource names
  policy_resource_group_name          = module.naming["management"].resource_group.name
  policy_log_analytics_workspace_name = module.naming["management"].log_analytics_workspace.name

  # DCR and UAI names - match defaults from avm-ptn-alz-management module
  # These use the module defaults as they're not generated by the naming module
  policy_dcr_change_tracking_name = try(var.management_resource_settings.data_collection_rules.change_tracking.name, "dcr-change-tracking")
  policy_dcr_defender_sql_name    = try(var.management_resource_settings.data_collection_rules.defender_sql.name, "dcr-defender-sql")
  policy_dcr_vm_insights_name     = try(var.management_resource_settings.data_collection_rules.vm_insights.name, "dcr-vm-insights")
  policy_uai_ama_name             = try(var.management_resource_settings.user_assigned_managed_identities.ama.name, "uai-ama")

  # Feature flags for DCRs
  dcr_change_tracking_enabled = try(var.management_resource_settings.data_collection_rules.change_tracking.enabled, true)
  dcr_defender_sql_enabled    = try(var.management_resource_settings.data_collection_rules.defender_sql.enabled, false)
  dcr_vm_insights_enabled     = try(var.management_resource_settings.data_collection_rules.vm_insights.enabled, true)
  uai_ama_enabled             = try(var.management_resource_settings.user_assigned_managed_identities.ama.enabled, true)

  # Policy values - only compute for enabled resources
  policy_values_from_resources = var.management_resources_enabled ? merge(
    # Change Tracking DCR (enabled by default)
    local.dcr_change_tracking_enabled ? {
      ama_change_tracking_data_collection_rule_id = provider::azapi::resource_group_resource_id(
        var.management_subscription_id,
        local.policy_resource_group_name,
        "Microsoft.Insights/dataCollectionRules",
        [local.policy_dcr_change_tracking_name]
      )
    } : {},
    # Defender for SQL DCR (disabled by default)
    local.dcr_defender_sql_enabled ? {
      ama_mdfc_sql_data_collection_rule_id = provider::azapi::resource_group_resource_id(
        var.management_subscription_id,
        local.policy_resource_group_name,
        "Microsoft.Insights/dataCollectionRules",
        [local.policy_dcr_defender_sql_name]
      )
    } : {},
    # VM Insights DCR (enabled by default)
    local.dcr_vm_insights_enabled ? {
      ama_vm_insights_data_collection_rule_id = provider::azapi::resource_group_resource_id(
        var.management_subscription_id,
        local.policy_resource_group_name,
        "Microsoft.Insights/dataCollectionRules",
        [local.policy_dcr_vm_insights_name]
      )
    } : {},
    # AMA User Assigned Identity (enabled by default)
    local.uai_ama_enabled ? {
      ama_user_assigned_managed_identity_id = provider::azapi::resource_group_resource_id(
        var.management_subscription_id,
        local.policy_resource_group_name,
        "Microsoft.ManagedIdentity/userAssignedIdentities",
        [local.policy_uai_ama_name]
      )
      ama_user_assigned_managed_identity_name = local.policy_uai_ama_name
    } : {},
    # Log Analytics Workspace (always created when management_resources_enabled)
    {
      log_analytics_workspace_id = provider::azapi::resource_group_resource_id(
        var.management_subscription_id,
        local.policy_resource_group_name,
        "Microsoft.OperationalInsights/workspaces",
        [local.policy_log_analytics_workspace_name]
      )
    }
  ) : {}

  # JSON-encoded for ALZ module (excludes null/empty values)
  policy_values_encoded = {
    for k, v in local.policy_values_from_resources :
    k => jsonencode({ value = v })
    if v != null && v != ""
  }

  policy_default_values = merge(
    local.policy_values_encoded,
    try(coalesce(var.management_group_settings.policy_default_values, {}), {})
  )

  # Microsoft Defender for Cloud policy assignment parameters
  # When microsoft_defender_settings is null (management_groups_enabled = false), try() returns
  # empty objects / false. These fallback values are irrelevant because module.management_groups
  # has count = 0.
  defender_plans       = try(var.microsoft_defender_settings.defender_plans, {})
  defender_subfeatures = try(var.microsoft_defender_settings.subfeatures, {})

  # Plan toggles → policy effect parameters (bool → "DeployIfNotExists" / "Disabled")
  defender_plan_parameters = {
    for param, enabled in {
      enableAscForAI                              = try(local.defender_plans.ai, false)
      enableAscForAppServices                     = try(local.defender_plans.app_services, false)
      enableAscForArm                             = try(local.defender_plans.arm, false)
      enableAscForContainers                      = try(local.defender_plans.containers, false)
      enableAscForCosmosDbs                       = try(local.defender_plans.cosmos_dbs, false)
      enableAscForCspm                            = try(local.defender_plans.cspm, false)
      enableAscForKeyVault                        = try(local.defender_plans.key_vault, false)
      enableAscForOssDb                           = try(local.defender_plans.oss_db, false)
      enableAscForServers                         = try(local.defender_plans.servers, false)
      enableAscForServersVulnerabilityAssessments = try(local.defender_plans.servers_vulnerability_assessments, false)
      enableAscForSql                             = try(local.defender_plans.sql, false)
      enableAscForSqlOnVm                         = try(local.defender_plans.sql_on_vm, false)
      enableAscForStorage                         = try(local.defender_plans.storage, false)
      enableTvmCheck                              = try(local.defender_plans.tvm_check, false)
    } : param => jsonencode({ value = enabled ? "DeployIfNotExists" : "Disabled" })
  }

  # Sub-feature toggles → policy boolean parameters (bool → "true" / "false")
  defender_subfeature_parameters = {
    for param, enabled in {
      ascForAIIsAIPromptEvidenceEnabled                              = try(local.defender_subfeatures.ai_prompt_evidence, false)
      ascForCspmIsAgentlessDiscoveryForKubernetesEnabled             = try(local.defender_subfeatures.cspm_agentless_discovery_for_kubernetes, false)
      ascForCspmIsAgentlessVmScanningEnabled                         = try(local.defender_subfeatures.cspm_agentless_vm_scanning, false)
      ascForCspmIsContainerRegistriesVulnerabilityAssessmentsEnabled = try(local.defender_subfeatures.cspm_container_registries_vulnerability_assessments, false)
      ascForCspmIsEntraPermissionsManagementEnabled                  = try(local.defender_subfeatures.cspm_entra_permissions_management, false)
      ascForCspmIsSensitiveDataDiscoveryEnabled                      = try(local.defender_subfeatures.cspm_sensitive_data_discovery, false)
      ascForServersIsAgentlessVmScanningEnabled                      = try(local.defender_subfeatures.servers_agentless_vm_scanning, false)
      ascForStorageIsOnUploadMalwareScanningEnabled                  = try(local.defender_subfeatures.storage_on_upload_malware_scanning, false)
      ascForStorageIsSensitiveDataDiscoveryEnabled                   = try(local.defender_subfeatures.storage_sensitive_data_discovery, false)
    } : param => jsonencode({ value = tostring(enabled) })
  }

  # Default policy assignments to modify (disables policies for features not deployed)
  # Note: Parameters must be JSON-encoded with { value = ... } format per ALZ module requirements
  default_policy_assignments_to_modify = {
    alz = {
      policy_assignments = {
        # Microsoft Defender for Cloud
        Deploy-MDFC-Config-H224 = {
          parameters = merge(
            {
              ascExportResourceGroupLocation = jsonencode({ value = var.location })
              ascExportResourceGroupName     = jsonencode({ value = try(var.microsoft_defender_settings.export_resource_group_name, "rg-asc-export") })
              emailSecurityContact           = jsonencode({ value = try(var.microsoft_defender_settings.email_security_contact, "") })
            },
            local.defender_plan_parameters,
            local.defender_subfeature_parameters,
          )
        }
      }
    }
    # NOTE: Enable-DDoS-VNET is removed from connectivity and landing_zones archetypes
    # in the lib/archetype_definitions/*_custom.alz_archetype_override.yaml files.
    # Only modify policies that exist in the architecture.
    corp = {
      policy_assignments = {
        Deploy-Private-DNS-Zones = {
          enforcement_mode = "DoNotEnforce"
        }
      }
    }
  }

  policy_assignments_to_modify = merge(
    local.default_policy_assignments_to_modify,
    try(coalesce(var.management_group_settings.policy_assignments_to_modify, {}), {})
  )
}
